language: java
before_install: 
  - ./msc/install-zeromq.sh
  - ./msc/install-jzmq.sh
install: ./script/ci/run_build.sh
after_install:
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email:
    recipients:
      - atsaltas@gmail.com
    on_success: always # [always|never|change] default change
    on_failure: always # [always|never|change] default always
